name: release
on:
  push:
    paths:
      - "ReduceMIUI.json"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 1. 准备文件
        run: |
          echo "version=$(jq .version $GITHUB_WORKSPACE/ReduceMIUI.json)" >> $GITHUB_ENV
          echo "versionCode=$(jq .versionCode $GITHUB_WORKSPACE/ReduceMIUI.json)" >> $GITHUB_ENV
          echo "ModuleFolderName=ReduceMIUI" >> $GITHUB_ENV
      - name: 2. 制作模块
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/GithubRelease
          echo "version=${{ env.version }}" >>$GITHUB_WORKSPACE/${{ env.ModuleFolderName }}/module.prop
          echo "versionCode=${{ env.versionCode }}" >>$GITHUB_WORKSPACE/${{ env.ModuleFolderName }}/module.prop
          cd $GITHUB_WORKSPACE/${{ env.ModuleFolderName }}
          zip -q -r ${{ env.ModuleFolderName }}.zip *
          mv $GITHUB_WORKSPACE/${{ env.ModuleFolderName }}/${{ env.ModuleFolderName }}.zip "$GITHUB_WORKSPACE"/GithubRelease/${{ env.ModuleFolderName }}.zip
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo "${{ env.ModuleFolderName }}.zip" > file.log
      - name: 3.上传到Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/GithubRelease/*
          name: "${{ env.ModuleFolderName }} ${{ env.version }}"
          tag: "${{ env.version }}"
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 4. 再次初始化仓库
        run: |
          rm -rf $GITHUB_WORKSPACE/*
      - uses: actions/checkout@v2
      - name: 5. 更新下载链接
        run: |
          git config --global user.email "30484319+zjw2017@users.noreply.github.com"
          git config --global user.name "柚稚的孩纸"
          sed -i '4d' $GITHUB_WORKSPACE/ReduceMIUI.json
          browser_download_url=$(curl -L   -H "Accept: application/vnd.github+json"   -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repos/zjw2017/${{ env.ModuleFolderName }}/releases/tags/${{ env.version }} | jq .assets[].browser_download_url | cut -d'"' -f2)
          sed -i '3a "zipUrl": "https://ghproxy.com/'"$browser_download_url"'",' $GITHUB_WORKSPACE/ReduceMIUI.json
          jq . $GITHUB_WORKSPACE/ReduceMIUI.json > $GITHUB_WORKSPACE/new.json
          rm -rf $GITHUB_WORKSPACE/ReduceMIUI.json && mv $GITHUB_WORKSPACE/new.json $GITHUB_WORKSPACE/ReduceMIUI.json
          git add ./ReduceMIUI.json
          git commit -m "v${{ env.version }}" -a
      - name: 6. 推送到Magisk Module仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
